# Generated by Django 3.1.4 on 2021-04-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateAuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('year', models.IntegerField()),
                ('mileage', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
