# Generated by Django 3.1.4 on 2021-04-07 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_auto_20210407_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={},
        ),
        migrations.AlterModelTable(
            name='signup',
            table='user',
        ),
    ]
