# Generated by Django 3.1.4 on 2021-04-08 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_auto_20210407_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='signup',
            table=None,
        ),
    ]
